## CONTENT LIST

1. Importing Libraries
2. Importing Data
3. Categorizing Products by Price_range using User-defined Functions
4. Categorizing Products by Price-range using loc() on Subset
5. Categorizing Products by Price_range using loc() on whole df
-  Task
6.1 Updating Busiest Day Column

## 1.  Importing Libraries

In [40]:
import pandas as pd
import numpy as np
import os

## 2. Importing Data

In [41]:
# Import df ords_prods_merged
ords_prods_merged = pd.read_pickle(r'C:\Users\heidi\OneDrive\CareerFoundry\Achievement4 Python Fundamentals for Data Analysts\4.2.Jupyter_Fundamentals_and_Python_Data_Types\Instacart Basket Analysis 16-03-2021\02 Data\Prepared data\orders_products_merged.pkl')

In [42]:
# Path
path = r'C:\Users\heidi\OneDrive\CareerFoundry\Achievement4 Python Fundamentals for Data Analysts\4.2.Jupyter_Fundamentals_and_Python_Data_Types\Instacart Basket Analysis 16-03-2021'

## 3. Categorizing Products by Price_range using User-defined Functions

In [43]:
#Create a subset of first 1000000 rows
df = ords_prods_merged[:1000000]

In [44]:
df.head()

,order_id,user_id,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices
0,2539329,1,1,2,8,11.11,196,1,0,both,Soda,77,7,9.0
1,2398795,1,2,3,7,15.00,196,1,1,both,Soda,77,7,9.0
2,473747,1,3,3,12,21.00,196,1,1,both,Soda,77,7,9.0
3,2254736,1,4,4,7,29.00,196,1,1,both,Soda,77,7,9.0
4,431534,1,5,4,15,28.00,196,1,1,both,Soda,77,7,9.0

In [45]:
df.shape

(1000000, 14)

In [46]:
# Define price function

def price_label(row):
    
    if row['prices'] <= 5:
        return 'Low-range product'
    elif (row['prices'] > 5) and (row['prices'] <= 15):
        return 'Mid-range product'
    elif row ['prices'] > 15:
        return 'High-range'
    else: return 'Not enough data'

In [47]:
# Imlementing new column title: price_range

df['price_range'] = df.apply(price_label, axis=1)

<ipython-input-47-384d33b9c9db>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis=1)

In [48]:
# Check the values in new column
df['price_range'].value_counts(dropna = False)

Mid-range product    756450
Low-range product    243550
Name: price_range, dtype: int64

In [49]:
#Check for the most expensive product in the subset
df['prices'].max()

14.8

In [50]:
df['price_range'].describe()

count               1000000
unique                    2
top       Mid-range product
freq                 756450
Name: price_range, dtype: object

## 4. Categorizing Products by Price-range using loc() on Subset

In [51]:
#Using the loc(function) to apply the conditional logic of an if-statement
df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

C:\Users\heidi\anaconda3\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
C:\Users\heidi\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [52]:
df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

C:\Users\heidi\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [53]:
df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

C:\Users\heidi\anaconda3\lib\site-packages\pandas\core\indexing.py:1765: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(loc, value)

In [54]:
# Checking values in new column
df['price_range_loc'].value_counts(dropna = False)

Mid-range product    756450
Low-range product    243550
Name: price_range_loc, dtype: int64

Using User-defined functions and loc() resulted in same value counts

## 5. Categorizing Products by Price_range using loc() on whole df

In [60]:
# df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'
ords_prods_merged.loc[ords_prods_merged['prices']>15, 'price_range_loc'] = 'High-range product'

In [61]:
ords_prods_merged.loc[(ords_prods_merged['prices'] <= 15) & (ords_prods_merged['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

In [62]:
ords_prods_merged.loc[ords_prods_merged['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [63]:
# Checking values in new column
ords_prods_merged['price_range_loc'].value_counts (dropna = False)

Mid-range product     21860860
Low-range product     10126321
High-range product      412551
Name: price_range_loc, dtype: int64

## TASK

## 6.1 Updating Busiest Day Column

In [64]:
# Frequency on 'orders_day_of_the_week' column. What items are being bought on busiest and slowest days

In [65]:
df['orders_day_of_the_week'].value_counts(dropna = False)

1    189421
0    184410
2    133958
5    130683
6    124839
3    119801
4    116888
Name: orders_day_of_the_week, dtype: int64

In [66]:
#Deduction: 0 = Sunday, has the highest frequency; 4 - Thursday has the lowest frequency

In [67]:
# Create new columns for “Busiest day,” “Least busy,” and “Regularly busy” using for-loop

In [72]:
result = []

for value in ords_prods_merged['orders_day_of_the_week']:
    if value == 0:
        result.append('Busiest day')
    elif value == 4:
        result.append('Least busy')
    else:
        result.append('Regular busy')

In [73]:
result

['Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Least busy',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 'Busiest day',
 'Busiest day',
 'Regular busy',
 'Regular busy',
 'Regular busy',
 ...]

In [74]:
# Create new column within df_ords_prods_merged and set it equal to result
ords_prods_merged['busiest_day'] = result

In [75]:
# Frequency of this new column
ords_prods_merged['busiest_day'].value_counts(dropna = False)

Regular busy    22413231
Busiest day      6203329
Least busy       3783172
Name: busiest_day, dtype: int64

Change “Busiest day” to “Busiest days” and slowest days to two slowest days (plural). 
Create new columns for this using a suitable method.

In [89]:
# Create new columns for “Two Busiest days,” “Two Least busiest,” and “Regular busy days.”
result_1 = []

for value in ords_prods_merged["orders_day_of_the_week"]:
  if value == 0 or value == 1:
    result_1.append("Busiest days")
  elif value == 3 or value == 4:
    result_1.append("Least busy")
  else:
    result_1.append("Regularly busy")

In [90]:
ords_prods_merged['busiest_days'] = result_1

In [91]:
# Check the values of this new column for accuracy
ords_prods_merged['busiest_days'].value_counts(dropna = False)

Regularly busy    12914068
Busiest days      11862627
Least busy         7623037
Name: busiest_days, dtype: int64

In [92]:
crosstab = pd.crosstab(ords_prods_merged['orders_day_of_the_week'], ords_prods_merged['busiest_days'], dropna = False)

In [93]:
# Copy crosstab to clipboard
crosstab.to_clipboard()

In [94]:
crosstab

busiest_days            Busiest days  Least busy  Regularly busy
orders_day_of_the_week
0                            6203329           0               0
1                            5659298           0               0
2                                  0           0         4213105
3                                  0     3839865               0
4                                  0     3783172               0
5                                  0           0         4205076
6                                  0           0         4495887

In [95]:
# Observations: Looking at the value counts in the 'order_dow'; By adding up 0 and 1, the result accurately reflects the results
# of the TWO Busiest days. This observation is also true for adding up the results of 3 and 4 of the value counts in the 
# 'order_dow' and the reflection of the results of the TWO Least busiest days.

## Question 4

When too many users make Instacart orders at the same time, the app freezes. The senior technical officer 
at Instacart wants you to identify the busiest hours of the day. Rather than by hour, they want periods of time labeled 
“Most orders,” “Average orders,” and “Fewest orders.” Create a new column containing these labels called 
“busiest_period_of_day.”

In [97]:
# Identify frequency of order hours
ords_prods_merged['order_hour_of_day'].value_counts(dropna = False)

10    2761333
11    2735694
14    2688728
15    2661718
13    2660570
12    2618104
16    2534744
9     2453842
17    2087273
8     1717863
18    1636226
19    1258076
20     976000
7      890923
21     795528
22     634159
23     402272
6      290450
0      218742
1      115683
5       87944
2       69360
4       53232
3       51268
Name: order_hour_of_day, dtype: int64

In [98]:
ords_prods_merged.head()

,order_id,user_id,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days
0,2539329,1,1,2,8,11.11,196,1,0,both,Soda,77,7,9.0,Mid-range product,Regular busy,Regularly busy
1,2398795,1,2,3,7,15.00,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regular busy,Least busy
2,473747,1,3,3,12,21.00,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regular busy,Least busy
3,2254736,1,4,4,7,29.00,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Least busy
4,431534,1,5,4,15,28.00,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Least busy

In [34]:
# Deduction: 10:00am is the MOST popular time to order and 3:00am the LEAST popular

In [254]:
# Create new columns for “Most orders,” “Average orders,” and “Fewest orders.”

In [102]:
result = []

for value in ords_prods_merged['order_hour_of_day']:
    if value >= 0 and value <= 6:
        result.append('Fewest orders')
    elif value >= 9 and value <= 17:
        result.append('Most orders')
    else: result.append('Average orders')

In [103]:
# Create column 'busiest_period_of_day'
ords_prods_merged['busiest_period_of_day'] = result

In [104]:
# Print frequency of new column
ords_prods_merged['busiest_period_of_day'].value_counts (dropna = False)

Most orders       23202006
Average orders     8311047
Fewest orders       886679
Name: busiest_period_of_day, dtype: int64

In [105]:
crosstab = pd.crosstab(ords_prods_merged['order_hour_of_day'], ords_prods_merged['busiest_period_of_day'], dropna = False)

In [106]:
# Copy crosstab to clipboard
crosstab.to_clipboard()

In [107]:
crosstab

busiest_period_of_day  Average orders  Fewest orders  Most orders
order_hour_of_day
0                                   0         218742            0
1                                   0         115683            0
2                                   0          69360            0
3                                   0          51268            0
4                                   0          53232            0
5                                   0          87944            0
6                                   0         290450            0
7                              890923              0            0
8                             1717863              0            0
9                                   0              0      2453842
10                                  0              0      2761333
11                                  0              0      2735694
12                                  0              0      2618104
13                                  0              0      2660570
14                                  0              0      2688728
15                                  0              0      2661718
16                                  0              0      2534744
17                                  0              0      2087273
18                            1636226              0            0
19                            1258076              0            0
20                             976000              0            0
21                             795528              0            0
22                             634159              0            0
23                             402272              0            0

In [110]:
ords_prods_merged.head()

,order_id,user_id,order_number,orders_day_of_the_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,11.11,196,1,0,both,Soda,77,7,9.0,Mid-range product,Regular busy,Regularly busy,Average orders
1,2398795,1,2,3,7,15.00,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regular busy,Least busy,Average orders
2,473747,1,3,3,12,21.00,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regular busy,Least busy,Most orders
3,2254736,1,4,4,7,29.00,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Least busy,Average orders
4,431534,1,5,4,15,28.00,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Least busy,Most orders

In [111]:
# The result indicates that the busiest times are between 9:00 and 4:00 when the day is divided into 3 slots of 8 
# starting from midnight.

In [113]:
ords_prods_merged.to_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'ords_prods_merged.pkl'))